// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrrnjyydgxdychsprcmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxycm5qeXlkZ3hkeWNoc3ByY21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTM5NTAsImV4cCI6MjA2MTI4OTk1MH0.HElztSHLpOt4gkEsx93f5v5TPRRh-rltqze7h-kerZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);