// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzjihytsbawknkqishn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2emppaHl0c2Jhd2tua3Fpc2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODYzMzAsImV4cCI6MjA2MTg2MjMzMH0.LFPA3uIaX81vwTecXvfw-TDpwC4utoD_Q1MV5noogwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);