// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfjkerifrcanlrjrjnih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmamtlcmlmcmNhbmxyanJqbmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjQxNDAsImV4cCI6MjA2NjIwMDE0MH0.b2Il4ItrSdtoLdwgGc_c-VvlJlPSg8XKsG_XmkNMApU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);